config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    resources :posts, controller: 'categories/posts'
  end

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts, dependent: :destroy
  
  before_create :set_auth_token

  private

    def set_auth_token
      return if auth_token.present?
      self.auth_token = generate_auth_token
    end

    def generate_auth_token
      loop do
        token = SecureRandom.hex
        break token unless self.class.exists?(auth_token: token)
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  protected

    def authenticate
      authenticate_token || render_unauthorized
    end

    def authenticate_token
      authenticate_with_http_token do |token, options|
        @current_user = User.find_by(auth_token: token)
      end
    end

    def render_unauthorized
      self.headers['WWW-Authenticate'] = 'Token realm = "Posts"'
      render json: 'Bad credentials', status: :unauthorized 
    end

    attr_reader :current_user

end

app/controllers/categories/posts_controller.rb
class Categories::PostsController < ApplicationController

  before_action :authenticate, except: [:index, :show]

  respond_to :json

  def new
    @category = Category.find(params[:category_id])
    @post = Post.new
  end

  def create
    @category = Category.find(params[:category_id])
    @post = current_user.posts.build(post_params)
    @post.category = @category
    if @post.save
      render json: @post.to_json, status: :created 
    else
      render json: @post.errors.full_messages, status: :unprocessable_entity 
    end
  end

  def show
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
  end

  def edit
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      render json: @post.to_json, status: :no_content 
    else
      render json: @post.errors.full_messages, status: :unprocessable_entity 
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
    @post.destroy
    head :no_content 
  end


  private

    def post_params
      params.require(:post).permit(:title, :body, :category_id)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authenticate, except: [:index, :show]

  respond_to :json

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      render json: @category.to_json, status: :created 
    else
      render json: @category.errors.full_messages, status: :unprocessable_entity 
    end
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      render json: @category.to_json, status: :no_content 
    else
      render json: @category.errors.full_messages, status: :unprocessable_entity 
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    head :no_content
  end

  private

    def category_params
      params.require(:category).permit(:title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<h2 class="headings">Categories</h2>

<% @categories.each do |category| %>
  <p class="capitalize"><%= link_to category.title, category %></p>
<% end %>

app/views/categories/posts/show.html.erb
<span class="pull-right"><%= link_to "All #{@category.title.capitalize} Blog Posts", category_path(@category) %></span>

<h3><%= @post.title %></h3>
<p><%= @post.body %></p>

app/views/categories/show.html.erb
<h2 class="headings"><%= @category.title.capitalize %> Blog Posts</h2>

<% @posts.each do |post| %>
  <p><%= link_to post.title, category_post_path(@category.id, post.id) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPostsApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

  <div class="container margin-top">

    <%= link_to "Home", "/", class: "home-nav" %>

<%= yield %>

  </div>

</body>
</html>